<a href="https://colab.research.google.com/github/Ferdyrahman2001/pemdas-ti11-sttnf-sem1/blob/main/Mkti11_10_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def jumlahin_matriks(m1, m2):
 return np.add(m1, m2)

#contoh
m1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #tanda "," menandakan baris
m2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

hasil = jumlahin_matriks(m1, m2)

print(hasil)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [1]:
import numpy as np

def invers_matriks(m):
  return np.linalg.inv(m)

m = [[1, 2, 3], [1, 2]]
hasil = invers_matriks(m)

print(hasil)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
import numpy as np

def perkalian_metriksv2(m1, m2):
    return np.dot(m1, m2)

m1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m2 = [[7, 8, 9], [6, 5, 4], [3, 2, 1]]

hasil = perkalian_metriksv2(m1, m2)

print(hasil)

[[ 28  24  20]
 [ 76  69  62]
 [124 114 104]]


In [ ]:
import numpy as np

def transpose_matriks(matriks):
    return np.transpose(matriks)

matriks = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

hasil = transpose_matriks(matriks)

print(hasil)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np

def ngurangin_matriks(m1, m2):
 return np.subtract(m1, m2)

#contoh
m1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #tanda "," menandakan baris
m2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

hasil = ngurangin_matriks(m1, m2)

print(hasil)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
import numpy as np

def perkalian_skalar_matriks(matriks, skalar):
 return np.multiply(matriks, skalar)

matriks = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
skalar = 2
hasil = perkalian_skalar_matriks(matriks, skalar)

print(hasil)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
